name: Branch Protection Rules

on:
  push:
    branches: [main, staging, production]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Configure main branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'security-scan',
                  'lint-test',
                  'infrastructure-validation',
                  'build-push'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 2
              },
              restrictions: {
                users: [],
                teams: ['security-team', 'devops-team']
              }
            });

            // Configure staging branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'staging',
              required_status_checks: {
                strict: true,
                contexts: [
                  'security-scan',
                  'lint-test',
                  'infrastructure-validation',
                  'build-push'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 2
              },
              restrictions: {
                users: [],
                teams: ['security-team', 'devops-team']
              }
            });

            // Configure production branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'production',
              required_status_checks: {
                strict: true,
                contexts: [
                  'security-scan',
                  'lint-test',
                  'infrastructure-validation',
                  'build-push'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 3
              },
              restrictions: {
                users: [],
                teams: ['security-team', 'devops-team', 'production-team']
              }
            });
